name: Jezyki Skryptowe URL SHORT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Backend build
        run: bash scripts/backend/build.sh

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Run unit tests
        run: bash scripts/backend/test.sh

  deploy_backend:
      name: Deploy backend to Render
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
      needs: build
      steps:
        - uses: actions/checkout@v4
        - name: Deploy DEV
          if: github.ref == 'refs/heads/dev'
          env:
            deploy_url_backend: ${{ secrets.RENDER_BACKEND_DEV_HOOK }}
          run: curl "$deploy_url_backend"
        - name: Deploy PROD
          if: github.ref == 'refs/heads/main'
          env:
            deploy_url_backend: ${{ secrets.RENDER_BACKEND_HOOK }}
          run: curl "$deploy_url_backend"

  deploy_frontend:
      name: Deploy frontend to Render
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
      needs: build
      steps:
        - uses: actions/checkout@v4
        - name: Deploy DEV
          if: github.ref == 'refs/heads/dev'
          env:
            deploy_url_frontend: ${{ secrets.RENDER_FRONTEND_DEV_HOOK }}
          run: curl "$deploy_url_frontend"
        - name: Deploy PROD
          if: github.ref == 'refs/heads/main'
          env:
            deploy_url_frontend: ${{ secrets.RENDER_FRONTEND_HOOK }}
          run: curl "$deploy_url_frontend"

  smoke_tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: deploy_backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Run smoke tests
        run: bash scripts/backend/smoke_test.sh
